In [7]:
import pandas as pn
from sklearn import datasets
import numpy as np
import math
from sklearn.model_selection import train_test_split

In [10]:
data=pn.read_csv("C:/Users/Moshiur/Desktop/Moshiur/Promoter/New Dataset/types_of_promoter.csv",header=None)
data=np.asarray(data)
data = np.delete(data, (0), axis=0)
data_len=len(data)
X=data[:,:data.shape[1]-1]
y=data[:,-1:]
X
data_len

2860

In [12]:
feature=[]
for i in range(data_len):
    ar=[]
    for j in range(81):
        if X[i,1][j]=='a' or X[i,1][j]=='A':ar.append(1)
        elif X[i,1][j]=='c' or X[i,1][j]=='C':ar.append(2)
        elif X[i,1][j]=='g' or X[i,1][j]=='G':ar.append(3)
        else :ar.append(0)
    feature.append(ar)
feature=np.asarray(feature)
feature = feature.reshape(data_len,81)
feature=np.concatenate((feature,y),axis=1)
#feature[1,:]
feature

array([[2, 1, 1, ..., 2, 1, 'sigma_24'],
       [2, 2, 3, ..., 2, 3, 'sigma_24'],
       [2, 1, 1, ..., 2, 2, 'sigma_24'],
       ...,
       [0, 1, 0, ..., 1, 1, 'sigma_70'],
       [1, 1, 0, ..., 1, 2, 'sigma_70'],
       [0, 2, 3, ..., 1, 2, 'sigma_70']], dtype=object)

In [14]:
dataframe = pn.DataFrame(feature)
dataframe.to_csv("C:/Users/Moshiur/Desktop/Moshiur/Promoter/New Dataset/types_of_promoter0123.csv")
#pn.DataFrame(data=all_promoter[1:,1:],index=data[1:,0],columns=all_promoter[0,1:])
dataframe.head()

  0  1  2  3  4  5  6  7  8  9     ...    72 73 74 75 76 77 78 79 80        81
0  2  1  1  2  2  1  3  2  1  1    ...     2  3  1  1  1  3  2  2  1  sigma_24
1  2  2  3  2  3  1  2  2  0  0    ...     2  2  1  0  0  3  2  2  3  sigma_24
2  2  1  1  3  1  3  2  0  3  3    ...     3  3  0  2  0  3  1  2  2  sigma_24
3  0  1  3  1  0  3  0  2  2  0    ...     1  0  2  1  2  2  3  1  1  sigma_24
4  0  1  0  0  0  0  1  0  2  0    ...     1  0  3  2  3  1  1  1  1  sigma_24

[5 rows x 82 columns]